// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASx6nb3j1DFrIUMExs4P-b11ts_YWzbdo',
    appId: '1:651491496899:web:bea7d535695a2c9aad6376',
    messagingSenderId: '651491496899',
    projectId: 'colombialugares',
    authDomain: 'colombialugares.firebaseapp.com',
    storageBucket: 'colombialugares.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrN0SYoaRYnM_Wd8iX4qw_CeD15qR9h2I',
    appId: '1:651491496899:android:7a517404492bd019ad6376',
    messagingSenderId: '651491496899',
    projectId: 'colombialugares',
    storageBucket: 'colombialugares.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgikrGJ3TCAobGI2XAyoTNy5WlWy52qDU',
    appId: '1:651491496899:ios:9771b9dbcd3e5cc0ad6376',
    messagingSenderId: '651491496899',
    projectId: 'colombialugares',
    storageBucket: 'colombialugares.firebasestorage.app',
    iosBundleId: 'com.example.flutterColombia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgikrGJ3TCAobGI2XAyoTNy5WlWy52qDU',
    appId: '1:651491496899:ios:9771b9dbcd3e5cc0ad6376',
    messagingSenderId: '651491496899',
    projectId: 'colombialugares',
    storageBucket: 'colombialugares.firebasestorage.app',
    iosBundleId: 'com.example.flutterColombia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASx6nb3j1DFrIUMExs4P-b11ts_YWzbdo',
    appId: '1:651491496899:web:108fe10d1c9af494ad6376',
    messagingSenderId: '651491496899',
    projectId: 'colombialugares',
    authDomain: 'colombialugares.firebaseapp.com',
    storageBucket: 'colombialugares.firebasestorage.app',
  );
}
